# The contents of this file are used by an IBM internal pipeline to onboard solutions to the IBM catalog
---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-cos-config
    kind: solution
    catalog_id: tbc
    offering_id: tbc
    variations:
      - name: static-website-configurator
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-private-path-vpc.sh"
        post_validation: "tests/scripts/post-validation-private-path-vpc.sh"
