# The contents of this file are used by an IBM internal pipeline to onboard solutions to the IBM catalog
---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-is-private-path-ext-conn
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 0be06773-9d63-439e-8211-c9787a0d27e7
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-private-path-vpc.sh"
        post_validation: "tests/scripts/post-validation-private-path-vpc.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
