# The contents of this file are used by an IBM internal pipeline to onboard solutions to the IBM catalog
---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-is-private-path-external-connectivity
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 7ca9901b-fe77-4c1e-9036-b9cf49e754f5
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-private-path-vpc.sh"
        post_validation: "tests/scripts/post-validation-private-path-vpc.sh"
