# The contents of this file are used by an IBM internal pipeline to onboard solutions to the IBM catalog
---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-is-private-path-external-connectivity
    kind: solution
    catalog_id:
    offering_id:
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-private-path-vpc.sh"
        post_validation: "tests/scripts/post-validation-private-path-vpc.sh"
